// <auto-generated />
namespace MieOELib.Data.Characters
{
    /*
     * 以下のクラスは Visual Studio 2017 の機能で JSONテキストから生成したものです。
     */
    public class MieOECharacters
    {
        public Gamedataobject[] GameDataObjects { get; set; }
    }

    public class Gamedataobject
    {
        public string MieGameDataTypeTag { get; set; }
        public string DebugName { get; set; }
        public string ID { get; set; }
        public Component[] Components { get; set; }
    }

    public class Component
    {
        public string MieGameDataTypeTag { get; set; }
        public string Controller { get; set; }
        public float ExitTime { get; set; }
        public string ClearProps { get; set; }
        public string ShowPropsOnInstant { get; set; }
        public string PropsID { get; set; }
        public string KithAnimation { get; set; }
        public string ValidCreatureRigID { get; set; }
        public string HideWeapons { get; set; }
        public string AnimationConversationSetting { get; set; }
        public string Type { get; set; }
        public int DisplayName { get; set; }
        public int SummaryText { get; set; }
        public int DescriptionText { get; set; }
        public string Icon { get; set; }
        public Skillslist[] SkillsList { get; set; }
        public string IsPlayerClass { get; set; }
        public int BaseDeflection { get; set; }
        public int BaseFortitude { get; set; }
        public int BaseReflexes { get; set; }
        public int BaseWill { get; set; }
        public int MeleeAccuracyBonus { get; set; }
        public int RangedAccuracyBonus { get; set; }
        public int MaxHealth { get; set; }
        public int HealthPerLevel { get; set; }
        public string CharacterStatsID { get; set; }
        public int KillsToMaster { get; set; }
        public int ExperienceMultiplier { get; set; }
        public string ParentObjectID { get; set; }
        public string PicturePath { get; set; }
        public int Description { get; set; }
        public string OverrideDamage { get; set; }
        public Primarydamage PrimaryDamage { get; set; }
        public Secondarydamage SecondaryDamage { get; set; }
        public object[] OverrideRevealPoints { get; set; }
        public string SlashEffect { get; set; }
        public string PierceEffect { get; set; }
        public string CrushEffect { get; set; }
        public string CanSheathe { get; set; }
        public Bone[] Bones { get; set; }
        public Charactercolliderdata[] CharacterColliderData { get; set; }
        public int DisplayNamePlural { get; set; }
        public string RequireSubclass { get; set; }
        public string PowerPoolIcon { get; set; }
        public string AccruedResourceIcon { get; set; }
        public string BaseStatsID { get; set; }
        public string IsSpellcaster { get; set; }
        public Spellcastsbypowerlevel[] SpellcastsByPowerLevel { get; set; }
        public int SpellIdentifierString { get; set; }
        public int SpellIdentifierStringPlural { get; set; }
        public string HasAccruedResource { get; set; }
        public int PowerPoolName { get; set; }
        public int AccruedResourceName { get; set; }
        public Lightcolor LightColor { get; set; }
        public Darkcolor DarkColor { get; set; }
        public string[] ProTierAttributesIDs { get; set; }
        public string[] GodTierAttributesIDs { get; set; }
        public Defaultdecisiontree DefaultDecisionTree { get; set; }
        public string Gender { get; set; }
        public string RaceID { get; set; }
        public string SubraceID { get; set; }
        public string CultureID { get; set; }
        public string CharacterProgressionTableID { get; set; }
        public int BaseClassLevel { get; set; }
        public string SpeakerID { get; set; }
        public string NakedArmorMaterial { get; set; }
        public string CreatureTypeGDID { get; set; }
        public string BestiaryEntryID { get; set; }
        public string BackgroundID { get; set; }
        public string[] KeywordsIDs { get; set; }
        public int BaseMight { get; set; }
        public int BaseConstitution { get; set; }
        public int BaseDexterity { get; set; }
        public int BasePerception { get; set; }
        public int BaseIntellect { get; set; }
        public int BaseResolve { get; set; }
        public string ImmuneToEngagement { get; set; }
        public string ImmuneToAttacks { get; set; }
        public string PerceptionType { get; set; }
        public string StealthDetectionID { get; set; }
        public string StealingAdjustmentID { get; set; }
        public int StartingMaxEngageableEnemyCount { get; set; }
        public float StartingAttackSpeedMultiplier { get; set; }
        public float StartingRateOfFireMultiplier { get; set; }
        public int StartingReloadTimeMultiplier { get; set; }
        public string PersonalityID { get; set; }
        public string AnimationAudioEventListID { get; set; }
        public int MinLevelAdjustment { get; set; }
        public int MaxLevelAdjustment { get; set; }
        public string IsNamedCharacter { get; set; }
        public string HeadID { get; set; }
        public string NeckID { get; set; }
        public string CapeID { get; set; }
        public string ChestID { get; set; }
        public string HandsID { get; set; }
        public string RightHandRingID { get; set; }
        public string LeftHandRingID { get; set; }
        public string FeetID { get; set; }
        public string WaistID { get; set; }
        public string GrimoireOrTrinketID { get; set; }
        public string PetID { get; set; }
        public Weaponset[] WeaponSets { get; set; }
        public string[] PropsIDs { get; set; }
        public string ForClassID { get; set; }
        public string HideInCharacterCreation { get; set; }
        public string Subclass { get; set; }
        public string CompanionGuidString { get; set; }
        public string ScriptName { get; set; }
        public Topic[] Topics { get; set; }
        public Topicreaction[] TopicReactions { get; set; }
        public Playerrelationship[] PlayerRelationship { get; set; }
        public Companionrelationship[] CompanionRelationships { get; set; }
        public string[] ProgressionTablesIDs { get; set; }
        public string IsSidekick { get; set; }
        public string GibDataID { get; set; }
        public string BloodDataID { get; set; }
        public string RigTypeID { get; set; }
        public string CanBePickpocketed { get; set; }
        public int Resolve { get; set; }
        public int Might { get; set; }
        public int Dexterity { get; set; }
        public int Intellect { get; set; }
        public int Constitution { get; set; }
        public int Perception { get; set; }
        public string[] CharacterCreationBackgroundsIDs { get; set; }
        public Hiteffect[] HitEffects { get; set; }
        public Deatheffect[] DeathEffects { get; set; }
        public string SigilID { get; set; }
        public float Radius { get; set; }
        public string IsAITargetable { get; set; }
        public int Acceleration { get; set; }
        public float AnimationRunSpeed { get; set; }
        public float AnimationWalkSpeed { get; set; }
        public float RunSpeed { get; set; }
        public float WalkSpeed { get; set; }
        public string ClipThroughObstacles { get; set; }
        public string CanFly { get; set; }
        public string CanJump { get; set; }
        public string OverrideDefaultRotationRates { get; set; }
        public int StationaryInCombatRotationRate { get; set; }
        public int StationaryOutOfCombatRotationRate { get; set; }
        public int MovingRotationRate { get; set; }
        public int MovingSubtleRotationRate { get; set; }
        public int MovingSubtleRotationThreshold { get; set; }
        public string SlogForceWalk { get; set; }
        public string SlogVFX { get; set; }
        public State[] States { get; set; }
        public string AudioEventListID { get; set; }
        public string PaladinOrderID { get; set; }
        public int Value { get; set; }
        public string AvailableInCharacterCreation { get; set; }
        public int LocalizedName { get; set; }
        public string DeityID { get; set; }
        public string[] CharacterCreationSubracesIDs { get; set; }
        public float Range { get; set; }
        public float PulseTime { get; set; }
        public string AbilityID { get; set; }
        public string WardItemID { get; set; }
        public int HearingRadius { get; set; }
        public int VisionAngle { get; set; }
        public int VisionDistance { get; set; }
        public string[] OptionalAbilityReferencesIDs { get; set; }
        public string CircularIcon { get; set; }
        public int NegativeDescription { get; set; }
        public int PositiveDescription { get; set; }
        public string Trigger { get; set; }
        public string InitialTrigger { get; set; }
        public Initializeconditions InitializeConditions { get; set; }
        public string SpeakerReferenceID { get; set; }
        public Conditionals Conditionals { get; set; }
        public int PartyLevel { get; set; }
        public Execscript[] ExecScripts { get; set; }
        public string Player { get; set; }
        public Partymember[] PartyMembers { get; set; }
        public int RelationshipScale { get; set; }
        public Relationshipthreshold1[] RelationshipThresholds { get; set; }
        public int ConversationDelay { get; set; }
        public string NudeBodyVisualData { get; set; }
        public Subraceappearancedata[] SubraceAppearanceDatas { get; set; }
        public Malehairlists MaleHairLists { get; set; }
        public Femalehairlists FemaleHairLists { get; set; }
        public Majorcolorlist[] MajorColorList { get; set; }
        public Tattoocolorlist[] TattooColorList { get; set; }
    }

    public class Primarydamage
    {
        public string DamageType { get; set; }
        public string AlternateDamageType { get; set; }
        public int Minimum { get; set; }
        public int Maximum { get; set; }
        public Damageproc[] DamageProcs { get; set; }
    }

    public class Damageproc
    {
        public string DamageType { get; set; }
        public float PercentOfBaseDamage { get; set; }
    }

    public class Secondarydamage
    {
        public string DamageType { get; set; }
        public string AlternateDamageType { get; set; }
        public int Minimum { get; set; }
        public int Maximum { get; set; }
        public object[] DamageProcs { get; set; }
    }

    public class Lightcolor
    {
        public int A { get; set; }
        public float R { get; set; }
        public float G { get; set; }
        public float B { get; set; }
    }

    public class Darkcolor
    {
        public int A { get; set; }
        public float R { get; set; }
        public float G { get; set; }
        public float B { get; set; }
    }

    public class Defaultdecisiontree
    {
        public string GuidString { get; set; }
    }

    public class Initializeconditions
    {
        public int Operator { get; set; }
        public object[] Components { get; set; }
    }

    public class Conditionals
    {
        public int Operator { get; set; }
        public object[] Components { get; set; }
    }

    public class Malehairlists
    {
        public Hairappearancepiece[] HairAppearancePieces { get; set; }
        public Facialhairappearancepiece[] FacialHairAppearancePieces { get; set; }
    }

    public class Hairappearancepiece
    {
        public string ModelVisualDataPath { get; set; }
    }

    public class Facialhairappearancepiece
    {
        public string ModelVisualDataPath { get; set; }
    }

    public class Femalehairlists
    {
        public Hairappearancepiece1[] HairAppearancePieces { get; set; }
        public object[] FacialHairAppearancePieces { get; set; }
    }

    public class Hairappearancepiece1
    {
        public string ModelVisualDataPath { get; set; }
    }

    public class Skillslist
    {
        public string SkillID { get; set; }
        public int Value { get; set; }
    }

    public class Bone
    {
        public string BoneName { get; set; }
        public string AttachPoint { get; set; }
        public Offset Offset { get; set; }
    }

    public class Offset
    {
        public float x { get; set; }
        public float y { get; set; }
        public float z { get; set; }
    }

    public class Charactercolliderdata
    {
        public string Race { get; set; }
        public string Gender { get; set; }
        public Capecollider[] CapeColliders { get; set; }
    }

    public class Capecollider
    {
        public string ColliderName { get; set; }
        public Position Position { get; set; }
        public Rotation Rotation { get; set; }
        public Scale Scale { get; set; }
        public Collidercenter ColliderCenter { get; set; }
        public float Radius { get; set; }
        public float Height { get; set; }
        public string Direction { get; set; }
        public string AttachmentBoneName { get; set; }
    }

    public class Position
    {
        public int x { get; set; }
        public int y { get; set; }
        public int z { get; set; }
    }

    public class Rotation
    {
        public int x { get; set; }
        public int y { get; set; }
        public float z { get; set; }
    }

    public class Scale
    {
        public int x { get; set; }
        public int y { get; set; }
        public int z { get; set; }
    }

    public class Collidercenter
    {
        public float x { get; set; }
        public float y { get; set; }
        public float z { get; set; }
    }

    public class Spellcastsbypowerlevel
    {
        public string[] Values { get; set; }
    }

    public class Weaponset
    {
        public string PrimaryWeaponID { get; set; }
        public string SecondaryWeaponID { get; set; }
    }

    public class Topic
    {
        public string TopicID { get; set; }
        public string Axis { get; set; }
        public string WeightID { get; set; }
        public Conditional Conditional { get; set; }
    }

    public class Conditional
    {
        public int Operator { get; set; }
        public Component1[] Components { get; set; }
    }

    public class Component1
    {
        public string MieGameDataTypeTag { get; set; }
        public int Operator { get; set; }
        public Component2[] Components { get; set; }
    }

    public class Component2
    {
        public string MieGameDataTypeTag { get; set; }
        public Data Data { get; set; }
        public bool Not { get; set; }
        public int Operator { get; set; }
    }

    public class Data
    {
        public string FullName { get; set; }
        public string[] Parameters { get; set; }
        public string Flags { get; set; }
        public string UnrealCall { get; set; }
        public int FunctionHash { get; set; }
        public int ParameterHash { get; set; }
    }

    public class Topicreaction
    {
        public string ChangeStrengthID { get; set; }
        public string Axis { get; set; }
        public Line[] Lines { get; set; }
    }

    public class Line
    {
        public int String { get; set; }
    }

    public class Playerrelationship
    {
        public string Threshold { get; set; }
        public Conversation Conversation { get; set; }
        public int Node { get; set; }
        public Conditionals1 Conditionals { get; set; }
    }

    public class Conversation
    {
        public string GuidString { get; set; }
    }

    public class Conditionals1
    {
        public int Operator { get; set; }
        public Component3[] Components { get; set; }
    }

    public class Component3
    {
        public string MieGameDataTypeTag { get; set; }
        public Data1 Data { get; set; }
        public bool Not { get; set; }
        public int Operator { get; set; }
    }

    public class Data1
    {
        public string FullName { get; set; }
        public string[] Parameters { get; set; }
        public string Flags { get; set; }
        public string UnrealCall { get; set; }
        public int FunctionHash { get; set; }
        public int ParameterHash { get; set; }
    }

    public class Companionrelationship
    {
        public string CompanionID { get; set; }
        public Relationshipthreshold[] RelationshipThresholds { get; set; }
    }

    public class Relationshipthreshold
    {
        public string Threshold { get; set; }
        public Conversation1 Conversation { get; set; }
        public int Node { get; set; }
        public Conditionals2 Conditionals { get; set; }
    }

    public class Conversation1
    {
        public string GuidString { get; set; }
    }

    public class Conditionals2
    {
        public int Operator { get; set; }
        public Component4[] Components { get; set; }
    }

    public class Component4
    {
        public string MieGameDataTypeTag { get; set; }
        public Data2 Data { get; set; }
        public bool Not { get; set; }
        public int Operator { get; set; }
        public Component5[] Components { get; set; }
    }

    public class Data2
    {
        public string FullName { get; set; }
        public string[] Parameters { get; set; }
        public string Flags { get; set; }
        public string UnrealCall { get; set; }
        public int FunctionHash { get; set; }
        public int ParameterHash { get; set; }
    }

    public class Component5
    {
        public string MieGameDataTypeTag { get; set; }
        public Data3 Data { get; set; }
        public bool Not { get; set; }
        public int Operator { get; set; }
    }

    public class Data3
    {
        public string FullName { get; set; }
        public string[] Parameters { get; set; }
        public string Flags { get; set; }
        public string UnrealCall { get; set; }
        public int FunctionHash { get; set; }
        public int ParameterHash { get; set; }
    }

    public class Hiteffect
    {
        public string KeywordID { get; set; }
        public string AbilityID { get; set; }
        public string SpawnedObject { get; set; }
        public int SelfDestructTimer { get; set; }
    }

    public class Deatheffect
    {
        public string KeywordID { get; set; }
        public string AbilityID { get; set; }
        public string SpawnedObject { get; set; }
        public int SelfDestructTimer { get; set; }
        public string CheckForWardItem { get; set; }
    }

    public class State
    {
        public string StateNameID { get; set; }
        public string Event { get; set; }
        public Conditions Conditions { get; set; }
        public string Instant { get; set; }
        public string[] TransitionsIDs { get; set; }
        public string UnloadStateID { get; set; }
        public Visualeffect[] VisualEffects { get; set; }
        public string[] AnimationsIDs { get; set; }
        public Mesh[] Meshes { get; set; }
    }

    public class Conditions
    {
        public int Operator { get; set; }
        public Component6[] Components { get; set; }
    }

    public class Component6
    {
        public string MieGameDataTypeTag { get; set; }
        public Data4 Data { get; set; }
        public bool Not { get; set; }
        public int Operator { get; set; }
    }

    public class Data4
    {
        public string FullName { get; set; }
        public string[] Parameters { get; set; }
        public string Flags { get; set; }
        public string UnrealCall { get; set; }
        public int FunctionHash { get; set; }
        public int ParameterHash { get; set; }
    }

    public class Visualeffect
    {
        public string VisualEffect { get; set; }
        public string AttachPoint { get; set; }
        public string AttachMode { get; set; }
        public string MeshType { get; set; }
        public string Loop { get; set; }
        public int AnimEventID { get; set; }
        public string Event { get; set; }
    }

    public class Mesh
    {
        public string MeshName { get; set; }
        public string Visible { get; set; }
        public int AnimEventID { get; set; }
        public string Event { get; set; }
    }

    public class Execscript
    {
        public string ExecScriptFile { get; set; }
    }

    public class Partymember
    {
        public string FilenameReference { get; set; }
    }

    public class Relationshipthreshold1
    {
        public string Threshold { get; set; }
        public float Value { get; set; }
    }

    public class Subraceappearancedata
    {
        public string Subrace { get; set; }
        public Maleheadappearancepiece[] MaleHeadAppearancePieces { get; set; }
        public Femaleheadappearancepiece[] FemaleHeadAppearancePieces { get; set; }
        public string CanHaveHair { get; set; }
        public string CanHaveFacialHair { get; set; }
        public Skincolor[] SkinColors { get; set; }
        public string ColorChannel1 { get; set; }
        public string ColorChannel2 { get; set; }
        public Haircolor[] HairColors { get; set; }
        public Eyecolor[] EyeColors { get; set; }
    }

    public class Maleheadappearancepiece
    {
        public string ModelVisualDataPath { get; set; }
    }

    public class Femaleheadappearancepiece
    {
        public string ModelVisualDataPath { get; set; }
    }

    public class Skincolor
    {
        public int A { get; set; }
        public float R { get; set; }
        public float G { get; set; }
        public float B { get; set; }
    }

    public class Haircolor
    {
        public int A { get; set; }
        public float R { get; set; }
        public float G { get; set; }
        public float B { get; set; }
    }

    public class Eyecolor
    {
        public int A { get; set; }
        public float R { get; set; }
        public float G { get; set; }
        public float B { get; set; }
    }

    public class Majorcolorlist
    {
        public int A { get; set; }
        public float R { get; set; }
        public float G { get; set; }
        public float B { get; set; }
    }

    public class Tattoocolorlist
    {
        public int A { get; set; }
        public float R { get; set; }
        public float G { get; set; }
        public float B { get; set; }
    }
}
