// <auto-generated />
namespace MieOELib.Data.Speakers
{
    public class MieOESpeakers
    {
        public Gamedataobject[] GameDataObjects { get; set; }
    }

    public class Gamedataobject
    {
        public string MieGameDataTypeTag { get; set; }
        public string DebugName { get; set; }
        public string ID { get; set; }
        public Component[] Components { get; set; }
    }

    public class Component
    {
        public string MieGameDataTypeTag { get; set; }
        public string Gender { get; set; }
        public string ChatterFile { get; set; }
        public string ExternalChatterVOID { get; set; }
        public string ChatterPrefix { get; set; }
        public string WwiseChatterEventOverride { get; set; }
        public string WwiseChatterVoiceOverride { get; set; }
    }
}
