// <auto-generated />
namespace MieOELib.Data.Chatter
{
    public class MieOEChatter
    {
        public Chatterfile[] ChatterFiles { get; set; }
    }

    public class Chatterfile
    {
        public string ID { get; set; }
        public string Filename { get; set; }
        public Audiolookup AudioLookup { get; set; }
        public string[] StringTableFilenames { get; set; }
        public Node[] Nodes { get; set; }
        public Classextender ClassExtender { get; set; }
    }

    public class Audiolookup
    {
        public string _22 { get; set; }
        public string _23 { get; set; }
        public string _25 { get; set; }
        public string _26 { get; set; }
        public string _27 { get; set; }
        public string _28 { get; set; }
        public string _29 { get; set; }
        public string _30 { get; set; }
        public string _31 { get; set; }
        public string _32 { get; set; }
        public string _33 { get; set; }
        public string _34 { get; set; }
        public string _35 { get; set; }
        public string _36 { get; set; }
        public string _37 { get; set; }
        public string _38 { get; set; }
        public string _39 { get; set; }
        public string _40 { get; set; }
        public string _41 { get; set; }
        public string _42 { get; set; }
        public string _43 { get; set; }
        public string _44 { get; set; }
        public string _45 { get; set; }
        public string _46 { get; set; }
        public string _47 { get; set; }
        public string _48 { get; set; }
        public string _49 { get; set; }
        public string _50 { get; set; }
        public string _51 { get; set; }
        public string _52 { get; set; }
        public string _53 { get; set; }
        public string _54 { get; set; }
        public string _55 { get; set; }
        public string _56 { get; set; }
        public string _57 { get; set; }
        public string _58 { get; set; }
        public string _59 { get; set; }
        public string _60 { get; set; }
        public string _61 { get; set; }
        public string _62 { get; set; }
        public string _63 { get; set; }
        public string _64 { get; set; }
        public string _65 { get; set; }
        public string _66 { get; set; }
        public string _67 { get; set; }
        public string _68 { get; set; }
        public string _69 { get; set; }
        public string _70 { get; set; }
        public string _71 { get; set; }
        public string _72 { get; set; }
        public string _73 { get; set; }
        public string _74 { get; set; }
        public string _75 { get; set; }
        public string _76 { get; set; }
        public string _10001 { get; set; }
        public string _20001 { get; set; }
        public string _20002 { get; set; }
        public string _20003 { get; set; }
        public string _20004 { get; set; }
        public string _20005 { get; set; }
        public string _20006 { get; set; }
        public string _30002 { get; set; }
        public string _40001 { get; set; }
        public string _40002 { get; set; }
        public string _40003 { get; set; }
        public string _40004 { get; set; }
        public string _40005 { get; set; }
        public string _40006 { get; set; }
        public string _40007 { get; set; }
        public string _40008 { get; set; }
        public string _40009 { get; set; }
        public string _40010 { get; set; }
        public string _40011 { get; set; }
        public string _50001 { get; set; }
        public string _50002 { get; set; }
        public string _50003 { get; set; }
        public string _60001 { get; set; }
        public string _60002 { get; set; }
        public string _60003 { get; set; }
        public string _70002 { get; set; }
        public string _70003 { get; set; }
        public string _70004 { get; set; }
        public string _70005 { get; set; }
        public string _70006 { get; set; }
        public string _77 { get; set; }
        public string _78 { get; set; }
        public string _79 { get; set; }
        public string _80 { get; set; }
        public string _81 { get; set; }
        public string _82 { get; set; }
        public string _83 { get; set; }
        public string _84 { get; set; }
        public string _85 { get; set; }
        public string _86 { get; set; }
        public string _87 { get; set; }
        public string _88 { get; set; }
        public string _89 { get; set; }
        public string _90 { get; set; }
        public string _91 { get; set; }
        public string _92 { get; set; }
        public string _93 { get; set; }
        public string _94 { get; set; }
        public string _95 { get; set; }
        public string _96 { get; set; }
        public string _98 { get; set; }
        public string _101 { get; set; }
        public string _102 { get; set; }
        public string _103 { get; set; }
        public string _104 { get; set; }
        public string _105 { get; set; }
        public string _106 { get; set; }
        public string _107 { get; set; }
        public string _108 { get; set; }
        public string _109 { get; set; }
        public string _110 { get; set; }
        public string _111 { get; set; }
        public string _112 { get; set; }
        public string _113 { get; set; }
        public string _114 { get; set; }
        public string _115 { get; set; }
        public string _120 { get; set; }
        public string _121 { get; set; }
        public string _122 { get; set; }
        public string _123 { get; set; }
        public string _124 { get; set; }
        public string _125 { get; set; }
        public string _126 { get; set; }
        public string _127 { get; set; }
        public string _128 { get; set; }
        public string _70001 { get; set; }
        public string _70007 { get; set; }
        public string _70009 { get; set; }
        public string _70010 { get; set; }
        public string _70011 { get; set; }
        public string _70012 { get; set; }
        public string _70013 { get; set; }
        public string _70014 { get; set; }
        public string _70015 { get; set; }
        public string _80002 { get; set; }
        public string _80003 { get; set; }
        public string _80004 { get; set; }
        public string _80005 { get; set; }
        public string _80006 { get; set; }
        public string _97 { get; set; }
        public string _99 { get; set; }
        public string _100 { get; set; }
        public string _116 { get; set; }
        public string _117 { get; set; }
        public string _118 { get; set; }
        public string _119 { get; set; }
        public string _129 { get; set; }
        public string _130 { get; set; }
        public string _131 { get; set; }
        public string _132 { get; set; }
        public string _133 { get; set; }
        public string _134 { get; set; }
        public string _135 { get; set; }
        public string _136 { get; set; }
        public string _137 { get; set; }
        public string _138 { get; set; }
        public string _139 { get; set; }
        public string _140 { get; set; }
        public string _141 { get; set; }
        public string _142 { get; set; }
        public string _143 { get; set; }
        public string _144 { get; set; }
        public string _4 { get; set; }
        public string _5 { get; set; }
        public string _6 { get; set; }
        public string _7 { get; set; }
        public string _8 { get; set; }
        public string _9 { get; set; }
        public string _10002 { get; set; }
        public string _10003 { get; set; }
        public string _10004 { get; set; }
        public string _10005 { get; set; }
        public string _10006 { get; set; }
        public string _10007 { get; set; }
        public string _10008 { get; set; }
        public string _10009 { get; set; }
        public string _10010 { get; set; }
        public string _10011 { get; set; }
        public string _20 { get; set; }
        public string _21 { get; set; }
        public string _24 { get; set; }
        public string _145 { get; set; }
        public string _146 { get; set; }
        public string _147 { get; set; }
        public string _150 { get; set; }
        public string _151 { get; set; }
        public string _152 { get; set; }
        public string _153 { get; set; }
        public string _154 { get; set; }
        public string _155 { get; set; }
        public string _156 { get; set; }
        public string _157 { get; set; }
        public string _158 { get; set; }
        public string _159 { get; set; }
        public string _160 { get; set; }
        public string _161 { get; set; }
        public string _162 { get; set; }
        public string _163 { get; set; }
        public string _164 { get; set; }
        public string _165 { get; set; }
        public string _166 { get; set; }
        public string _168 { get; set; }
        public string _169 { get; set; }
        public string _170 { get; set; }
        public string _171 { get; set; }
        public string _172 { get; set; }
        public string _173 { get; set; }
        public string _174 { get; set; }
        public string _175 { get; set; }
        public string _176 { get; set; }
        public string _177 { get; set; }
        public string _178 { get; set; }
        public string _179 { get; set; }
        public string _180 { get; set; }
        public string _181 { get; set; }
        public string _182 { get; set; }
        public string _183 { get; set; }
        public string _184 { get; set; }
        public string _185 { get; set; }
        public string _186 { get; set; }
        public string _187 { get; set; }
        public string _188 { get; set; }
        public string _189 { get; set; }
        public string _190 { get; set; }
        public string _191 { get; set; }
        public string _192 { get; set; }
        public string _193 { get; set; }
        public string _194 { get; set; }
        public string _195 { get; set; }
        public string _196 { get; set; }
        public string _197 { get; set; }
        public string _198 { get; set; }
        public string _199 { get; set; }
        public string _200 { get; set; }
        public string _201 { get; set; }
        public string _202 { get; set; }
        public string _203 { get; set; }
        public string _204 { get; set; }
        public string _205 { get; set; }
        public string _206 { get; set; }
        public string _207 { get; set; }
        public string _208 { get; set; }
        public string _209 { get; set; }
        public string _210 { get; set; }
        public string _212 { get; set; }
        public string _213 { get; set; }
        public string _215 { get; set; }
        public string _216 { get; set; }
        public string _217 { get; set; }
        public string _218 { get; set; }
        public string _219 { get; set; }
        public string _220 { get; set; }
        public string _221 { get; set; }
        public string _222 { get; set; }
        public string _224 { get; set; }
        public string _225 { get; set; }
        public string _226 { get; set; }
        public string _227 { get; set; }
        public string _228 { get; set; }
        public string _229 { get; set; }
        public string _230 { get; set; }
        public string _231 { get; set; }
        public string _232 { get; set; }
        public string _233 { get; set; }
        public string _234 { get; set; }
        public string _235 { get; set; }
        public string _236 { get; set; }
        public string _237 { get; set; }
        public string _238 { get; set; }
        public string _239 { get; set; }
        public string _240 { get; set; }
        public string _241 { get; set; }
        public string _242 { get; set; }
        public string _243 { get; set; }
        public string _244 { get; set; }
        public string _19 { get; set; }
        public string _148 { get; set; }
        public string _149 { get; set; }
        public string _167 { get; set; }
        public string _211 { get; set; }
        public string _214 { get; set; }
        public string _223 { get; set; }
        public string _2 { get; set; }
        public string _3 { get; set; }
        public string _11 { get; set; }
        public string _12 { get; set; }
        public string _13 { get; set; }
        public string _14 { get; set; }
        public string _15 { get; set; }
        public string _16 { get; set; }
        public string _17 { get; set; }
        public string _18 { get; set; }
        public string _10012 { get; set; }
        public string _20057 { get; set; }
        public string _20058 { get; set; }
        public string _20059 { get; set; }
        public string _20060 { get; set; }
        public string _20062 { get; set; }
        public string _20063 { get; set; }
        public string _20064 { get; set; }
        public string _20042 { get; set; }
        public string _20065 { get; set; }
        public string _20066 { get; set; }
        public string _20067 { get; set; }
        public string _20068 { get; set; }
        public string _20069 { get; set; }
        public string _20070 { get; set; }
        public string _20052 { get; set; }
        public string _20082 { get; set; }
        public string _20080 { get; set; }
        public string _20081 { get; set; }
        public string _20007 { get; set; }
        public string _20008 { get; set; }
        public string _20009 { get; set; }
        public string _20010 { get; set; }
        public string _20011 { get; set; }
        public string _20012 { get; set; }
        public string _20013 { get; set; }
        public string _20014 { get; set; }
        public string _20015 { get; set; }
        public string _20016 { get; set; }
        public string _20017 { get; set; }
        public string _20018 { get; set; }
        public string _20020 { get; set; }
        public string _20021 { get; set; }
        public string _20022 { get; set; }
        public string _20023 { get; set; }
        public string _20025 { get; set; }
        public string _20026 { get; set; }
        public string _20037 { get; set; }
        public string _20038 { get; set; }
        public string _20039 { get; set; }
        public string _20040 { get; set; }
        public string _20084 { get; set; }
        public string _20041 { get; set; }
        public string _20044 { get; set; }
        public string _20045 { get; set; }
        public string _20046 { get; set; }
        public string _20047 { get; set; }
        public string _20049 { get; set; }
        public string _20050 { get; set; }
        public string _20051 { get; set; }
        public string _20074 { get; set; }
        public string _20075 { get; set; }
        public string _20076 { get; set; }
        public string _20077 { get; set; }
        public string _20078 { get; set; }
        public string _20079 { get; set; }
        public string _20083 { get; set; }
        public string _20028 { get; set; }
        public string _20029 { get; set; }
        public string _20030 { get; set; }
        public string _20031 { get; set; }
        public string _20032 { get; set; }
        public string _20033 { get; set; }
        public string _20034 { get; set; }
        public string _20035 { get; set; }
        public string _10 { get; set; }
        public string _10057 { get; set; }
        public string _10058 { get; set; }
        public string _10059 { get; set; }
        public string _10060 { get; set; }
        public string _10062 { get; set; }
        public string _10063 { get; set; }
        public string _10064 { get; set; }
        public string _10042 { get; set; }
        public string _10065 { get; set; }
        public string _10066 { get; set; }
        public string _10067 { get; set; }
        public string _10068 { get; set; }
        public string _10069 { get; set; }
        public string _10070 { get; set; }
        public string _10052 { get; set; }
        public string _10082 { get; set; }
        public string _10080 { get; set; }
        public string _10081 { get; set; }
        public string _10013 { get; set; }
        public string _10014 { get; set; }
        public string _10015 { get; set; }
        public string _10016 { get; set; }
        public string _10017 { get; set; }
        public string _10018 { get; set; }
        public string _10020 { get; set; }
        public string _10021 { get; set; }
        public string _10022 { get; set; }
        public string _10023 { get; set; }
        public string _10025 { get; set; }
        public string _10026 { get; set; }
        public string _10037 { get; set; }
        public string _10038 { get; set; }
        public string _10039 { get; set; }
        public string _10040 { get; set; }
        public string _10084 { get; set; }
        public string _10041 { get; set; }
        public string _10044 { get; set; }
        public string _10045 { get; set; }
        public string _10046 { get; set; }
        public string _10047 { get; set; }
        public string _10049 { get; set; }
        public string _10050 { get; set; }
        public string _10051 { get; set; }
        public string _10074 { get; set; }
        public string _10075 { get; set; }
        public string _10076 { get; set; }
        public string _10077 { get; set; }
        public string _10078 { get; set; }
        public string _10079 { get; set; }
        public string _10083 { get; set; }
        public string _10028 { get; set; }
        public string _10029 { get; set; }
        public string _10030 { get; set; }
        public string _10031 { get; set; }
        public string _10032 { get; set; }
        public string _10033 { get; set; }
        public string _10034 { get; set; }
        public string _10035 { get; set; }
        public string _245 { get; set; }
        public string _246 { get; set; }
        public string _247 { get; set; }
        public string _248 { get; set; }
        public string _249 { get; set; }
        public string _250 { get; set; }
        public string _251 { get; set; }
        public string _252 { get; set; }
        public string _253 { get; set; }
        public string _254 { get; set; }
        public string _255 { get; set; }
        public string _257 { get; set; }
        public string _258 { get; set; }
        public string _259 { get; set; }
        public string _260 { get; set; }
        public string _261 { get; set; }
        public string _262 { get; set; }
        public string _263 { get; set; }
        public string _264 { get; set; }
        public string _265 { get; set; }
        public string _266 { get; set; }
        public string _267 { get; set; }
        public string _268 { get; set; }
        public string _269 { get; set; }
        public string _270 { get; set; }
        public string _271 { get; set; }
        public string _272 { get; set; }
        public string _273 { get; set; }
        public string _275 { get; set; }
        public string _276 { get; set; }
        public string _277 { get; set; }
        public string _278 { get; set; }
        public string _279 { get; set; }
        public string _280 { get; set; }
        public string _281 { get; set; }
        public string _282 { get; set; }
        public string _283 { get; set; }
        public string _298 { get; set; }
        public string _299 { get; set; }
        public string _300 { get; set; }
        public string _301 { get; set; }
        public string _302 { get; set; }
        public string _303 { get; set; }
        public string _304 { get; set; }
        public string _305 { get; set; }
        public string _306 { get; set; }
        public string _307 { get; set; }
        public string _308 { get; set; }
        public string _309 { get; set; }
        public string _310 { get; set; }
        public string _311 { get; set; }
        public string _312 { get; set; }
        public string _313 { get; set; }
        public string _314 { get; set; }
        public string _315 { get; set; }
        public string _316 { get; set; }
        public string _317 { get; set; }
        public string _318 { get; set; }
        public string _256 { get; set; }
        public string _274 { get; set; }
        public string _293 { get; set; }
        public string _294 { get; set; }
        public string _295 { get; set; }
        public string _296 { get; set; }
        public string _297 { get; set; }
        public string _289 { get; set; }
        public string _290 { get; set; }
        public string _291 { get; set; }
        public string _292 { get; set; }
        public string _319 { get; set; }
        public string _320 { get; set; }
        public string _321 { get; set; }
        public string _322 { get; set; }
        public string _323 { get; set; }
        public string _324 { get; set; }
        public string _284 { get; set; }
        public string _286 { get; set; }
        public string _288 { get; set; }
        public string _10056 { get; set; }
        public string _10094 { get; set; }
        public string _10095 { get; set; }
        public string _10096 { get; set; }
        public string _10097 { get; set; }
        public string _10098 { get; set; }
        public string _10099 { get; set; }
        public string _10100 { get; set; }
        public string _10101 { get; set; }
        public string _10102 { get; set; }
        public string _10103 { get; set; }
        public string _10104 { get; set; }
        public string _10105 { get; set; }
        public string _10106 { get; set; }
        public string _10107 { get; set; }
        public string _10085 { get; set; }
        public string _10086 { get; set; }
        public string _10087 { get; set; }
        public string _10088 { get; set; }
        public string _10089 { get; set; }
        public string _10090 { get; set; }
        public string _10091 { get; set; }
        public string _10092 { get; set; }
        public string _10093 { get; set; }
        public string _10061 { get; set; }
        public string _10071 { get; set; }
        public string _10072 { get; set; }
        public string _10073 { get; set; }
        public string _10048 { get; set; }
        public string _10019 { get; set; }
        public string _1 { get; set; }
        public string _10043 { get; set; }
        public string _10024 { get; set; }
        public string _10027 { get; set; }
        public string _10054 { get; set; }
        public string _10053 { get; set; }
        public string _10055 { get; set; }
        public string _60004 { get; set; }
        public string _60005 { get; set; }
        public string _60006 { get; set; }
    }

    public class Classextender
    {
        public object[] ExtendedProperties { get; set; }
    }

    public class Node
    {
        public string MieChatterNodeDataTypeTag { get; set; }
        public bool NotSkippable { get; set; }
        public bool IsQuestionNode { get; set; }
        public bool HideSpeaker { get; set; }
        public bool IsTempText { get; set; }
        public bool PlayVOAs3DSound { get; set; }
        public int PlayType { get; set; }
        public int Persistence { get; set; }
        public int NoPlayRandomWeight { get; set; }
        public int VOPositioning { get; set; }
        public int DisplayType { get; set; }
        public int NodeID { get; set; }
        public Component Component { get; set; }
        public int ContainerNodeID { get; set; }
        public Link[] Links { get; set; }
        public Classextender1 ClassExtender { get; set; }
        public Conditionals Conditionals { get; set; }
        public Onenterscript[] OnEnterScripts { get; set; }
        public object[] OnExitScripts { get; set; }
        public object[] OnUpdateScripts { get; set; }
        public bool RequiresValidChildNode { get; set; }
    }

    public class Component
    {
        public string MieChatterNodeDataTypeTag { get; set; }
        public Overrides Overrides { get; set; }
    }

    public class Overrides
    {
        public string EventType { get; set; }
        public int Priority { get; set; }
        public float Cooldown { get; set; }
        public string OnInterrupt { get; set; }
        public string InterruptionLevel { get; set; }
        public string OnQueued { get; set; }
        public float MaxWaitTime { get; set; }
        public string ChatterPrefix { get; set; }
    }

    public class Classextender1
    {
        public string[] ExtendedProperties { get; set; }
    }

    public class Conditionals
    {
        public int Operator { get; set; }
        public Component1[] Components { get; set; }
    }

    public class Component1
    {
        public string type { get; set; }
        public Data Data { get; set; }
        public bool Not { get; set; }
        public int Operator { get; set; }
        public Component2[] Components { get; set; }
    }

    public class Data
    {
        public string FullName { get; set; }
        public string[] Parameters { get; set; }
        public string Flags { get; set; }
        public string UnrealCall { get; set; }
        public int FunctionHash { get; set; }
        public int ParameterHash { get; set; }
    }

    public class Component2
    {
        public string type { get; set; }
        public Data1 Data { get; set; }
        public bool Not { get; set; }
        public int Operator { get; set; }
    }

    public class Data1
    {
        public string FullName { get; set; }
        public string[] Parameters { get; set; }
        public string Flags { get; set; }
        public string UnrealCall { get; set; }
        public int FunctionHash { get; set; }
        public int ParameterHash { get; set; }
    }

    public class Link
    {
        public string type { get; set; }
        public int RandomWeight { get; set; }
        public int FromNodeID { get; set; }
        public int ToNodeID { get; set; }
        public bool PointsToGhost { get; set; }
        public Conditionals1 Conditionals { get; set; }
        public Classextender2 ClassExtender { get; set; }
    }

    public class Conditionals1
    {
        public int Operator { get; set; }
        public object[] Components { get; set; }
    }

    public class Classextender2
    {
        public object[] ExtendedProperties { get; set; }
    }

    public class Onenterscript
    {
        public Data2 Data { get; set; }
        public Conditional Conditional { get; set; }
    }

    public class Data2
    {
        public string FullName { get; set; }
        public string[] Parameters { get; set; }
        public string Flags { get; set; }
        public string UnrealCall { get; set; }
        public int FunctionHash { get; set; }
        public int ParameterHash { get; set; }
    }

    public class Conditional
    {
        public int Operator { get; set; }
        public object[] Components { get; set; }
    }
}
