// <auto-generated />
namespace MieOELib.Data.Conversations
{
    public class MieOEConversations
    {
        public Conversation[] Conversations { get; set; }
    }

    public class Conversation
    {
        public string ID { get; set; }
        public string Filename { get; set; }
        public Conversationscriptnode ConversationScriptNode { get; set; }
        public int ConversationType { get; set; }
        public Charactermapping[] CharacterMappings { get; set; }
        public Node[] Nodes { get; set; }
        public Classextender1 ClassExtender { get; set; }
    }

    public class Conversationscriptnode
    {
        public bool RequiresValidChildNode { get; set; }
        public bool NotSkippable { get; set; }
        public bool IsQuestionNode { get; set; }
        public bool HideSpeaker { get; set; }
        public bool IsTempText { get; set; }
        public bool PlayVOAs3DSound { get; set; }
        public int PlayType { get; set; }
        public int Persistence { get; set; }
        public int NoPlayRandomWeight { get; set; }
        public int VOPositioning { get; set; }
        public int DisplayType { get; set; }
        public int NodeID { get; set; }
        public int ContainerNodeID { get; set; }
        public object[] Links { get; set; }
        public Classextender ClassExtender { get; set; }
        public Conditionals Conditionals { get; set; }
        public object[] OnEnterScripts { get; set; }
        public object[] OnExitScripts { get; set; }
        public object[] OnUpdateScripts { get; set; }
    }

    public class Classextender
    {
        public object[] ExtendedProperties { get; set; }
    }

    public class Conditionals
    {
        public int Operator { get; set; }
        public object[] Components { get; set; }
    }

    public class Classextender1
    {
        public string[] ExtendedProperties { get; set; }
    }

    public class Charactermapping
    {
        public string Guid { get; set; }
        public string InstanceTag { get; set; }
    }

    public class Node
    {
        public string MieFlowChartsDataTypeTag { get; set; }
        public string EmotionType { get; set; }
        public float EmotionStrength { get; set; }
        public bool PersistEmotion { get; set; }
        public float EmotionDelay { get; set; }
        public string SpeakerGuid { get; set; }
        public string ListenerGuid { get; set; }
        public string ExternalVO { get; set; }
        public bool HasVO { get; set; }
        public bool NotSkippable { get; set; }
        public bool IsQuestionNode { get; set; }
        public bool HideSpeaker { get; set; }
        public bool IsTempText { get; set; }
        public bool PlayVOAs3DSound { get; set; }
        public int PlayType { get; set; }
        public int Persistence { get; set; }
        public int NoPlayRandomWeight { get; set; }
        public int VOPositioning { get; set; }
        public int DisplayType { get; set; }
        public int NodeID { get; set; }
        public int ContainerNodeID { get; set; }
        public Link[] Links { get; set; }
        public Classextender2 ClassExtender { get; set; }
        public Conditionals1 Conditionals { get; set; }
        public Onenterscript[] OnEnterScripts { get; set; }
        public object[] OnExitScripts { get; set; }
        public object[] OnUpdateScripts { get; set; }
        public int BankNodePlayType { get; set; }
        public int[] ChildNodeIDs { get; set; }
        public bool RequiresValidChildNode { get; set; }
    }

    public class Classextender2
    {
        public string[] ExtendedProperties { get; set; }
    }

    public class Conditionals1
    {
        public int Operator { get; set; }
        public Component[] Components { get; set; }
    }

    public class Component
    {
        public string type { get; set; }
        public Data Data { get; set; }
        public bool Not { get; set; }
        public int Operator { get; set; }
    }

    public class Data
    {
        public string FullName { get; set; }
        public string[] Parameters { get; set; }
        public string Flags { get; set; }
        public string UnrealCall { get; set; }
        public int FunctionHash { get; set; }
        public int ParameterHash { get; set; }
    }

    public class Link
    {
        public string type { get; set; }
        public int RandomWeight { get; set; }
        public bool PlayQuestionNodeVO { get; set; }
        public int QuestionNodeTextDisplay { get; set; }
        public int FromNodeID { get; set; }
        public int ToNodeID { get; set; }
        public bool PointsToGhost { get; set; }
        public Conditionals2 Conditionals { get; set; }
        public Classextender3 ClassExtender { get; set; }
    }

    public class Conditionals2
    {
        public int Operator { get; set; }
        public object[] Components { get; set; }
    }

    public class Classextender3
    {
        public object[] ExtendedProperties { get; set; }
    }

    public class Onenterscript
    {
        public Data1 Data { get; set; }
        public Conditional Conditional { get; set; }
    }

    public class Data1
    {
        public string FullName { get; set; }
        public string[] Parameters { get; set; }
        public string Flags { get; set; }
        public string UnrealCall { get; set; }
        public int FunctionHash { get; set; }
        public int ParameterHash { get; set; }
    }

    public class Conditional
    {
        public int Operator { get; set; }
        public object[] Components { get; set; }
    }
}
