// <auto-generated />
namespace MieOELib.Data.Quests
{
    public class MieOEQuests
    {
        public Quest[] Quests { get; set; }
    }

    public class Quest
    {
        public string ID { get; set; }
        public string Filename { get; set; }
        public Event[] Events { get; set; }
        public int?[] AddendumIDs { get; set; }
        public int?[] AlternateDescriptionIDs { get; set; }
        public int QuestType { get; set; }
        public Node[] Nodes { get; set; }
        public Classextender ClassExtender { get; set; }
    }

    public class Classextender
    {
        public string[] ExtendedProperties { get; set; }
    }

    public class Event
    {
        public string MieQuestsNodeDataTypeTag { get; set; }
        public string VariableName { get; set; }
        public int VariableValue { get; set; }
        public string ExternalVariableValue { get; set; }
        public int EventType { get; set; }
        public int EventID { get; set; }
    }

    public class Node
    {
        public string MieQuestsNodeDataTypeTag { get; set; }
        public bool IsTempText { get; set; }
        public int LinkEvaluation { get; set; }
        public object ObjectiveRootNode { get; set; }
        public Endstate[] EndStates { get; set; }
        public int?[] AlternateDescriptionIDs { get; set; }
        public int ExperienceType { get; set; }
        public int ExperienceLevel { get; set; }
        public int NodeID { get; set; }
        public int ContainerNodeID { get; set; }
        public Link[] Links { get; set; }
        public Classextender1 ClassExtender { get; set; }
        public Conditionals Conditionals { get; set; }
        public Onenterscript[] OnEnterScripts { get; set; }
        public object[] OnExitScripts { get; set; }
        public object[] OnUpdateScripts { get; set; }
        public int DescriptionID { get; set; }
        public int?[] AddendumIDs { get; set; }
        public object[] WaypointsJson { get; set; }
        public int ExperienceWeight { get; set; }
        public int DisplayType { get; set; }
        public int SortGroup { get; set; }
        public bool Failed { get; set; }
        public int EndStateID { get; set; }
    }

    public class Classextender1
    {
        public object[] ExtendedProperties { get; set; }
    }

    public class Conditionals
    {
        public int Operator { get; set; }
        public Component[] Components { get; set; }
    }

    public class Component
    {
        public string MieQuestsNodeDataTypeTag { get; set; }
        public Data Data { get; set; }
        public bool Not { get; set; }
        public int Operator { get; set; }
        public Component1[] Components { get; set; }
    }

    public class Data
    {
        public string FullName { get; set; }
        public string[] Parameters { get; set; }
        public string Flags { get; set; }
        public string UnrealCall { get; set; }
        public int FunctionHash { get; set; }
        public int ParameterHash { get; set; }
    }

    public class Component1
    {
        public string MieQuestsNodeDataTypeTag { get; set; }
        public Data1 Data { get; set; }
        public bool Not { get; set; }
        public int Operator { get; set; }
        public Component2[] Components { get; set; }
    }

    public class Data1
    {
        public string FullName { get; set; }
        public string[] Parameters { get; set; }
        public string Flags { get; set; }
        public string UnrealCall { get; set; }
        public int FunctionHash { get; set; }
        public int ParameterHash { get; set; }
    }

    public class Component2
    {
        public string MieQuestsNodeDataTypeTag { get; set; }
        public Data2 Data { get; set; }
        public bool Not { get; set; }
        public int Operator { get; set; }
        public Component3[] Components { get; set; }
    }

    public class Data2
    {
        public string FullName { get; set; }
        public string[] Parameters { get; set; }
        public string Flags { get; set; }
        public string UnrealCall { get; set; }
        public int FunctionHash { get; set; }
        public int ParameterHash { get; set; }
    }

    public class Component3
    {
        public string MieQuestsNodeDataTypeTag { get; set; }
        public Data3 Data { get; set; }
        public bool Not { get; set; }
        public int Operator { get; set; }
    }

    public class Data3
    {
        public string FullName { get; set; }
        public string[] Parameters { get; set; }
        public string Flags { get; set; }
        public string UnrealCall { get; set; }
        public int FunctionHash { get; set; }
        public int ParameterHash { get; set; }
    }

    public class Endstate
    {
        public int DescriptionID { get; set; }
        public int EndStateID { get; set; }
        public int PackageID { get; set; }
    }

    public class Link
    {
        public string MieQuestsNodeDataTypeTag { get; set; }
        public bool RequiredToExitObjective { get; set; }
        public bool FailObjective { get; set; }
        public int FromNodeID { get; set; }
        public int ToNodeID { get; set; }
        public bool PointsToGhost { get; set; }
        public Conditionals1 Conditionals { get; set; }
        public Classextender2 ClassExtender { get; set; }
    }

    public class Conditionals1
    {
        public int Operator { get; set; }
        public object[] Components { get; set; }
    }

    public class Classextender2
    {
        public object[] ExtendedProperties { get; set; }
    }

    public class Onenterscript
    {
        public Data4 Data { get; set; }
        public Conditional Conditional { get; set; }
    }

    public class Data4
    {
        public string FullName { get; set; }
        public string[] Parameters { get; set; }
        public string Flags { get; set; }
        public string UnrealCall { get; set; }
        public int FunctionHash { get; set; }
        public int ParameterHash { get; set; }
    }

    public class Conditional
    {
        public int Operator { get; set; }
        public Component4[] Components { get; set; }
    }

    public class Component4
    {
        public string MieQuestsNodeDataTypeTag { get; set; }
        public Data5 Data { get; set; }
        public bool Not { get; set; }
        public int Operator { get; set; }
    }

    public class Data5
    {
        public string FullName { get; set; }
        public string[] Parameters { get; set; }
        public string Flags { get; set; }
        public string UnrealCall { get; set; }
        public int FunctionHash { get; set; }
        public int ParameterHash { get; set; }
    }
}
